// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class Booklist
    {
        public string Tensach { get; set; }
        public string Tacgia { get; set; }
        public string Theloai { get; set; }
        public string TenNxb { get; set; }
        public int NamXb { get; set; }
        public int Soban { get; set; }
        public string VitriHang { get; set; }
        public string VitriKe { get; set; }
    }
}