// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class Muon
    {
        public Muon()
        {
            Tras = new HashSet<Tra>();
        }

        public int MuonId { get; set; }
        public string Masosinhvien { get; set; }
        public int SinhvienId { get; set; }
        public int ThuthuId { get; set; }
        public int SachId { get; set; }
        public DateTime Ngaymuon { get; set; }

        public virtual Sach Sach { get; set; }
        public virtual Sinhvien Sinhvien { get; set; }
        public virtual Thuthu Thuthu { get; set; }
        public virtual ICollection<Tra> Tras { get; set; }
    }
}