// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class NhaXb
    {
        public NhaXb()
        {
            Saches = new HashSet<Sach>();
        }

        public int NhaXbid { get; set; }
        public string Tenxuatban { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string ThongtinNguoiDaiDien { get; set; }

        public virtual ICollection<Sach> Saches { get; set; }
    }
}