// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class Tacgia
    {
        public Tacgia()
        {
            Saches = new HashSet<Sach>();
        }

        public int TacgiaId { get; set; }
        public string Tentacgia { get; set; }
        public DateTime Ngaysinh { get; set; }

        public virtual ICollection<Sach> Saches { get; set; }
    }
}