// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class TheLoai
    {
        public TheLoai()
        {
            Saches = new HashSet<Sach>();
        }

        public int TheloaiId { get; set; }
        public string Tentheloai { get; set; }

        public virtual ICollection<Sach> Saches { get; set; }
    }
}