// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class Tra
    {
        public int TraId { get; set; }
        public int MuonId { get; set; }
        public int ThuthuId { get; set; }
        public DateTime Ngaytra { get; set; }

        public virtual Muon Muon { get; set; }
        public virtual Thuthu Thuthu { get; set; }
    }
}