// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace qltv.Models
{
    public partial class Vitri
    {
        public Vitri()
        {
            Saches = new HashSet<Sach>();
        }

        public int VitriId { get; set; }
        public string Tenhang { get; set; }
        public string Soke { get; set; }

        public virtual ICollection<Sach> Saches { get; set; }
    }
}